apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluegreendeployment
spec:
  replicas: 3 # Set the number of desired replicas
  selector:
    matchLabels:
      app: bluegreen
  template:
    metadata:
      labels:
        app: bluegreen
    spec:
      containers:
      - name: bluegreendep-v1
        image: AssignDevOps26/bluegreendep-v1:latest
        ports:
        - containerPort: 80

