apiVersion: v1
kind: Service
metadata:
  name: greenservice
spec:
  selector:
    app: green
  ports:
  - protocol: TCP
    port: 8006 # Expose port 8006 on the Service
    targetPort: 80
  type: NodePort

