apiVersion: apps/v1
kind: Deployment
metadata:
  name: greendeployment
spec:
  replicas: 3 # Set the number of desired replicas
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: bluegreendep-v2
        image: AssignDevOps26/bluegreendep-v2:latest
        ports:
        - containerPort: 80


